remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-minimal
title: Hoang Son's CV
description: Hi there, thanks for coming. Please let me know if you have any questions or recommendations.
